[[constraint]]
  branch = "master"
  name = "github.com/84codes/go-api"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.12.0"

[prune]
  go-tests = true
  unused-packages = true
